name: Create Release on Push

on:
  push:
    branches:
      - main
    paths:
      - 'manifest.json'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read manifest version
        id: get_version
        run: |
          VERSION=$(grep '"version"' manifest.json | head -1 | sed -E 's/[^0-9]*([0-9.]+).*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Zip Chrome Extension
        run: |
          zip -r ugcnet-extension-${{ steps.get_version.outputs.version }}.zip . -x '*.git*' '*.github*'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: UGC NET Extension v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          files: ugcnet-extension-${{ steps.get_version.outputs.version }}.zip
